version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    env_file:
      - .env
  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./docker_data/pgadmin4/data:/var/lib/postgresql/data
    depends_on:
      - db
  web:
    build: .
    command:
      [
        "./wait-for-it.sh",
        "db",
        "5432",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000"
      ]
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: